backend:
  name: git-gateway          # Netlify Identity ↔ GitHub bridge
  branch: main               # adjust if you publish from another branch

media_folder: "dist/assets"  # where uploads are saved *inside* the repo
public_folder: "/dist/assets" # how the browser reaches them

collections:
  - name: gallery
    label: "Gallery"
    files:
      - file: "gallery.json"         # CMS maintains this file
        label: "Photo order"
        fields:
          - name: images
            label: "Images"
            widget: list
            allow_add: true
            collapsed: false
            fields:
              - { name: src, label: "File", widget: image }
              - { name: alt, label: "Alt text", widget: string }
