backend:
  name: git-gateway
  branch: main

media_folder: "dist/assets"
public_folder: "/dist/assets"

collections:
  - name: gallery
    label: "Gallery"
    files:
      - name: list            # ← required identifier (any slug‑safe string)
        label: "Photo order"
        file: "gallery.json"
        fields:
          - name: images
            label: "Images"
            widget: list
            allow_add: true
            collapsed: false
            fields:
              - { name: src, label: "File", widget: image }
              - { name: alt, label: "Alt text", widget: string }
